### ISSUE TITLE
Great! Some suggestions

### ISSUE THREAD

**Issue by gwillem** [serverdensity/sd-python-wrapper#3]
Is this for your internal use only, or for SD customers? If the latter, great! Some humble requests:

- Drop dependency on mongo
- Revert requirements dependency (requirements_dev should include requirements)
- Drop specific version pinning from requirements, otherwise its hard to integrate this in an existing project

Best!

**Comment by jonathan-s** [comment]
Hello @gwillem! 
This is for SD customers. 

So the reason we have a dependency on pymongo at the moment is that the library has built in validation that if have a property that needs it checks if it's a valid objectId. However I'm open to other ways of checking whether it's valid objectId other than using `from bson.objectid import ObjectId`

Good point about the requirements. 

I'll change the version to >= instead. That should help with integrating it into an existing project, right?

The wrapper still have a few kinks that need ironed out. If you discover anything, please let me know and I'll get on it. :)

Cheers!

**Comment by jonathan-s** [comment]
Hi @gwillem, 

An update on this. The dependency of pymongo still hasn't been dropped. `requirements.txt` no longer imports `requirements_dev.txt`, so that has been fixed. With regards to specific version pinning, I have just removed the version pinning from setup.py and deployed that.

**Comment by gwillem** [comment]
I see you have been busy, well done! FYI I needed a quick solution to query SD for many metrics/devices so I spiked a quick minimal client: https://github.com/gwillem/serverdensity-query

**Comment by jonathan-s** [comment]
Thanks for letting me take a peek into how you use the api. The most noticable to me in the code that you provide is the transformations you do on the available metrics to be more humanreadable. Which makes sense since it's for a CLI app. Perhaps it would help to implement that directly into the wrapper as well. I've found that to be a pain point too.  

Let me know if there is anything else in particular that you would like to see in the wrapper and we'll take that into consideration :).

**Comment by jonathan-s** [comment]
The latest version no longer contains pymongo. So all issues that you raised are fixed now.
